version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - "3333:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    networks:
      - rs_ws_env_nw
  app:
    image: node:fermium-alpine
    command: npm run dev:server
    container_name: rentx
    restart: "on-failure"
    ports:
      - "3000:3000"
    volumes:
      - .:/user/app
    working_dir: /user/app
    networks:
      - rs_ws_env_nw
    depends_on:
      - database_ignite

volumes:
  pgdata:
    driver: local

networks:
  rs_ws_env_nw:
